-- Sequence Builder shared drafting workspace.
-- Additive ledger step: independent from LH2-synchronized campaign_steps.

SET ROLE app_owner;

CREATE TABLE public.sequence_documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    document jsonb NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    created_by uuid NOT NULL,
    created_by_name text NOT NULL,
    updated_by uuid NOT NULL,
    updated_by_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sequence_documents_pkey PRIMARY KEY (id),
    CONSTRAINT sequence_documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
    CONSTRAINT sequence_documents_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
    CONSTRAINT sequence_documents_name_check CHECK ((char_length(btrim(name)) >= 1) AND (char_length(name) <= 160)),
    CONSTRAINT sequence_documents_document_check CHECK (jsonb_typeof(document) = 'object'),
    CONSTRAINT sequence_documents_revision_check CHECK (revision > 0)
);

CREATE TABLE public.sequence_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sequence_id uuid NOT NULL,
    revision integer NOT NULL,
    name text NOT NULL,
    document jsonb NOT NULL,
    saved_by uuid NOT NULL,
    saved_by_name text NOT NULL,
    saved_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sequence_versions_pkey PRIMARY KEY (id),
    CONSTRAINT sequence_versions_sequence_id_fkey FOREIGN KEY (sequence_id) REFERENCES public.sequence_documents(id) ON DELETE CASCADE,
    CONSTRAINT sequence_versions_saved_by_fkey FOREIGN KEY (saved_by) REFERENCES public.users(id),
    CONSTRAINT sequence_versions_sequence_revision_key UNIQUE (sequence_id, revision),
    CONSTRAINT sequence_versions_revision_check CHECK (revision > 0),
    CONSTRAINT sequence_versions_document_check CHECK (jsonb_typeof(document) = 'object')
);

CREATE TABLE public.sequence_comment_threads (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sequence_id uuid NOT NULL,
    step_id text,
    variation_id text,
    anchor jsonb,
    created_by uuid NOT NULL,
    created_by_name text NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by uuid,
    resolved_by_name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sequence_comment_threads_pkey PRIMARY KEY (id),
    CONSTRAINT sequence_comment_threads_sequence_id_fkey FOREIGN KEY (sequence_id) REFERENCES public.sequence_documents(id) ON DELETE CASCADE,
    CONSTRAINT sequence_comment_threads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
    CONSTRAINT sequence_comment_threads_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id),
    CONSTRAINT sequence_comment_threads_step_id_check CHECK ((step_id IS NULL) OR ((char_length(btrim(step_id)) >= 1) AND (char_length(step_id) <= 100))),
    CONSTRAINT sequence_comment_threads_variation_id_check CHECK ((variation_id IS NULL) OR ((char_length(btrim(variation_id)) >= 1) AND (char_length(variation_id) <= 100))),
    CONSTRAINT sequence_comment_threads_anchor_check CHECK ((anchor IS NULL) OR (jsonb_typeof(anchor) = 'object')),
    CONSTRAINT sequence_comment_threads_resolution_check CHECK (
        (resolved_at IS NULL AND resolved_by IS NULL AND resolved_by_name IS NULL)
        OR (resolved_at IS NOT NULL AND resolved_by IS NOT NULL AND resolved_by_name IS NOT NULL)
    )
);

CREATE TABLE public.sequence_comment_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thread_id uuid NOT NULL,
    author_id uuid NOT NULL,
    author_name text NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sequence_comment_messages_pkey PRIMARY KEY (id),
    CONSTRAINT sequence_comment_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.sequence_comment_threads(id) ON DELETE CASCADE,
    CONSTRAINT sequence_comment_messages_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id),
    CONSTRAINT sequence_comment_messages_body_check CHECK ((char_length(btrim(body)) >= 1) AND (char_length(body) <= 4000))
);

CREATE INDEX sequence_documents_active_updated_idx
    ON public.sequence_documents (archived, updated_at DESC, id);
CREATE INDEX sequence_versions_sequence_revision_idx
    ON public.sequence_versions (sequence_id, revision DESC);
CREATE INDEX sequence_comment_threads_sequence_updated_idx
    ON public.sequence_comment_threads (sequence_id, updated_at DESC, id);
CREATE INDEX sequence_comment_messages_thread_created_idx
    ON public.sequence_comment_messages (thread_id, created_at, id);

CREATE TRIGGER touch_sequence_documents_updated_at
    BEFORE UPDATE ON public.sequence_documents
    FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER touch_sequence_comment_threads_updated_at
    BEFORE UPDATE ON public.sequence_comment_threads
    FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE public.sequence_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sequence_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sequence_comment_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sequence_comment_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY sequence_documents_active_member ON public.sequence_documents
    FOR ALL TO app_runtime, app_readonly
    USING (public.is_active_team_member())
    WITH CHECK (public.is_active_team_member());
CREATE POLICY sequence_versions_active_member ON public.sequence_versions
    FOR ALL TO app_runtime, app_readonly
    USING (public.is_active_team_member())
    WITH CHECK (public.is_active_team_member());
CREATE POLICY sequence_comment_threads_active_member ON public.sequence_comment_threads
    FOR ALL TO app_runtime, app_readonly
    USING (public.is_active_team_member())
    WITH CHECK (public.is_active_team_member());
CREATE POLICY sequence_comment_messages_active_member ON public.sequence_comment_messages
    FOR ALL TO app_runtime, app_readonly
    USING (public.is_active_team_member())
    WITH CHECK (public.is_active_team_member());

REVOKE ALL ON TABLE
    public.sequence_documents,
    public.sequence_versions,
    public.sequence_comment_threads,
    public.sequence_comment_messages
    FROM PUBLIC;

GRANT SELECT ON TABLE
    public.sequence_documents,
    public.sequence_versions,
    public.sequence_comment_threads,
    public.sequence_comment_messages
    TO app_runtime, app_readonly;

GRANT INSERT, UPDATE ON TABLE
    public.sequence_documents,
    public.sequence_comment_threads
    TO app_runtime;
GRANT INSERT ON TABLE
    public.sequence_versions,
    public.sequence_comment_messages
    TO app_runtime;

GRANT USAGE, SELECT ON SEQUENCE
    public.sequence_versions_id_seq,
    public.sequence_comment_messages_id_seq
    TO app_runtime;

ALTER TABLE public.sequence_documents OWNER TO app_owner;
ALTER TABLE public.sequence_versions OWNER TO app_owner;
ALTER TABLE public.sequence_comment_threads OWNER TO app_owner;
ALTER TABLE public.sequence_comment_messages OWNER TO app_owner;
ALTER SEQUENCE public.sequence_versions_id_seq OWNER TO app_owner;
ALTER SEQUENCE public.sequence_comment_messages_id_seq OWNER TO app_owner;

RESET ROLE;
