-- GENERATED BY THE CANDIDATE, NOT APPLIED ANYWHERE PERMANENT.
--
-- This is `getMigrations(options).compileMigrations()` from Better Auth 1.6.25,
-- with the `admin` plugin and the `canonicalUserId` additional field enabled —
-- i.e. the exact DDL the candidate requires, emitted by the candidate rather
-- than transcribed by hand. `tests/candidateSchema.test.ts` re-generates it and
-- fails if this file drifts, so it cannot silently go stale.
--
-- Recorded because it is what S17 has to hand to the migration ledger, and
-- because its shape is an input to G3:
--
--   * four tables — `user`, `session`, `account`, `verification`
--   * `user.id` is `text`, not `uuid`. It is a provider subject, and it belongs
--     in `public.user_identities.provider_subject`; it is NOT a canonical
--     `public.users.id` and must never be joined to one.
--   * `user.email` is UNIQUE here and also lives on `public.team_members`.
--     Two writable copies of an address is the one genuine duplication between
--     the stores, and the atomic-invite transaction is what keeps them equal.
--   * `account.password` holds the scrypt hash. Nothing else in the product
--     may hold a grant on this table.
--   * `canonicalUserId` is the spike's addition: a *proposal*, confirmed by RLS
--     before it becomes an actor. It is not needed at all if the owner accepts
--     `sql/candidate_identity_resolver.sql` instead.
--
-- The spike creates these in a dedicated `identity_spike` schema owned by a
-- dedicated role, never in `public`. See `tests/storeIsolation.test.ts`.
--
-- Applied to: the spike's ephemeral clean-room container only. NOT to the Neon
-- project, NOT to Supabase, and NOT to postgres/tenant-baseline/.

-- BEGIN GENERATED
create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "role" text, "banned" boolean, "banReason" text, "banExpires" timestamptz, "canonicalUserId" text);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade, "impersonatedBy" text);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");
