/**
 * Sizing guard: every size in the product comes from the density scale.
 *
 * docs/ui-standard.md "Density" defines one type scale and one set of insets
 * and gaps, all in src/styles/tokens.css. A raw `padding: 18px`, a Tailwind
 * `gap-2.5` or a `text-xs` bypasses it — the route drifts off the scale, and
 * the next density change misses it. This reads the source as text and fails
 * on every literal that should have been a token, naming file and line.
 *
 * Out of scope, with the reason:
 * - src/styles/tokens.css — the one place values are defined.
 * - src/components/ui/** — shadcn's generated components; they follow shadcn's
 *   own scale and are regenerated by `shadcn add`, so hand edits would be lost.
 * - `.linkedin-*` selectors — the LinkedIn message preview imitates an external
 *   surface (exception 4 in ui-standard.md "What is not allowed").
 */
import { describe, expect, it } from 'vitest'
import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

const SRC = join(__dirname, '../src')

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) walk(path, out)
    else out.push(path)
  }
  return out
}

const files = walk(SRC).map((path) => relative(SRC, path).split('\\').join('/'))
const isExcluded = (file: string) => file === 'styles/tokens.css' || file.startsWith('components/ui/')

/** Blank out comments but keep newlines, so reported line numbers stay true. */
function stripComments(text: string, jsx: boolean): string {
  const blank = (match: string) => match.replace(/[^\n]/g, ' ')
  let out = text.replace(/\/\*[\s\S]*?\*\//g, blank)
  if (jsx) out = out.replace(/(^|[^:'"`])\/\/[^\n]*/g, (match, lead: string) => lead + blank(match.slice(lead.length)))
  return out
}

function lineOf(text: string, index: number): number {
  return text.slice(0, index).split('\n').length
}

// ---- CSS -------------------------------------------------------------------

const SPACING_PROPERTY = /^(padding|margin|gap|row-gap|column-gap)(-[a-z-]+)?$/
const TYPE_PROPERTY = /^(font-size|line-height)$/
/** 1–2px is allowed for borders and icon alignment; nothing else is a literal. */
const HAIRLINE = new Set(['0', '0px', '1px', '2px', '-1px', '-2px'])

/** Literal lengths left in a value once var(), and calc() built on a var(), are removed. */
function literalLengths(value: string): string[] {
  let rest = value.replace(/calc\(([^()]*var\([^()]*\)[^()]*)\)/g, '')
  rest = rest.replace(/var\([^()]*\)/g, '')
  return rest.match(/-?\d*\.?\d+(px|rem|em)\b/g) ?? []
}

function cssViolations(file: string, source: string): string[] {
  const css = stripComments(source, false)
  const found: string[] = []
  const rule = /([^{}]+)\{([^{}]*)\}/g
  let match = rule.exec(css)
  while (match) {
    const selector = match[1].trim()
    const body = match[2]
    const bodyStart = match.index + match[0].indexOf('{') + 1
    if (!selector.includes('.linkedin-') && !selector.startsWith('@')) {
      const declaration = /([a-z-]+)\s*:\s*([^;]+)/g
      let decl = declaration.exec(body)
      while (decl) {
        const [, property, value] = decl
        const at = `${file}:${lineOf(css, bodyStart + decl.index)}`
        if (SPACING_PROPERTY.test(property)) {
          for (const literal of literalLengths(value)) {
            if (!HAIRLINE.has(literal)) found.push(`${at}  ${selector} { ${property}: ${value.trim()} } — use a space / inset / gap token`)
          }
        }
        if (TYPE_PROPERTY.test(property)) {
          const bare = value.replace(/var\([^()]*\)/g, '').replace(/!important/, '').trim()
          const allowed = bare === '' || /^(inherit|normal|1|0|initial|unset)$/.test(bare) || (property === 'font-size' && /^(inherit|100%)$/.test(bare))
          if (!allowed) found.push(`${at}  ${selector} { ${property}: ${value.trim()} } — use a --text-* / --leading-* token`)
        }
        decl = declaration.exec(body)
      }
    }
    match = rule.exec(css)
  }
  return found
}

// ---- TSX -------------------------------------------------------------------

/** Tailwind spacing with a numeric or arbitrary value. `0`, `px` and `0.5` (2px) stay allowed. */
const TW_SPACING = /(?<![\w-])-?(p|px|py|pt|pb|pl|pr|ps|pe|m|mx|my|mt|mb|ml|mr|ms|me|gap|gap-x|gap-y|space-x|space-y)-(\d+(?:\.\d+)?|\[[^\]\s]+\])(?![\w.\]-])/g
/** Tailwind's own type scale (text-xs is 12px, under the 13px floor) and any arbitrary size or leading. */
const TW_TYPE = /(?<![\w-])(text-(?:xs|sm|base|lg|xl|[2-9]xl)|text-\[(?:length:)?[^\]\s]+\]|leading-(?:\[[^\]\s]+\]|tight|snug|normal|relaxed|loose|\d+))(?![\w-])/g
/** Inline styles and chart props that hard-code a size. */
const INLINE_SIZE = /\b(padding|margin|gap|rowGap|columnGap|fontSize|lineHeight)(Top|Bottom|Left|Right|Inline|Block)?\s*:\s*['"]?-?\d/g

function tsxViolations(file: string, source: string): string[] {
  const code = stripComments(source, true)
  const found: string[] = []
  for (const match of code.matchAll(TW_SPACING)) {
    const value = match[2]
    if (value === '0' || value === '0.5') continue
    found.push(`${file}:${lineOf(code, match.index ?? 0)}  ${match[0]} — use an app-* step or a density utility (p-card, px-pane, gap-section, gap-group, gap-stack, gap-inline)`)
  }
  for (const match of code.matchAll(TW_TYPE)) {
    found.push(`${file}:${lineOf(code, match.index ?? 0)}  ${match[0]} — use text-app-meta / table / body / subsection / section / page / kpi`)
  }
  for (const match of code.matchAll(INLINE_SIZE)) {
    if (/:\s*['"]?0['"]?\s*[,}]/.test(code.slice(match.index ?? 0, (match.index ?? 0) + match[0].length + 3))) continue
    found.push(`${file}:${lineOf(code, match.index ?? 0)}  ${match[0]}… — take the size from a token or a named constant`)
  }
  return found
}

describe('sizing scale', () => {
  const cssFiles = files.filter((file) => file.endsWith('.css') && !isExcluded(file))
  const tsxFiles = files.filter((file) => file.endsWith('.tsx') && !isExcluded(file))

  it('finds the sources it is meant to check', () => {
    expect(cssFiles).toContain('ui/ui.css')
    expect(cssFiles).not.toContain('styles/tokens.css')
    expect(tsxFiles).toContain('pages/Replies.tsx')
    expect(tsxFiles.some((file) => file.startsWith('components/ui/'))).toBe(false)
  })

  it('catches what it claims to catch', () => {
    // Mutation check: without it every other assertion here could pass vacuously.
    expect(cssViolations('x.css', '.a { padding: 18px; gap: var(--space-sm); }')).toHaveLength(1)
    expect(cssViolations('x.css', '.a { margin: calc(var(--space-sm) - 3px) 0 1px; }')).toHaveLength(0)
    expect(cssViolations('x.css', '.a { font-size: 15px; line-height: 1.45; }')).toHaveLength(2)
    expect(cssViolations('x.css', '.linkedin-bubble { padding: 10px 13px; font-size: 13px; }')).toHaveLength(0)
    expect(tsxViolations('x.tsx', '<div className="gap-2.5 p-4 mt-0.5 m-0 text-xs leading-[1.5] text-app-meta" />')).toHaveLength(4)
    expect(tsxViolations('x.tsx', '<div className="px-app-md gap-section p-[var(--space-md)]" />')).toHaveLength(1)
    expect(tsxViolations('x.tsx', '<Tick style={{ fontSize: 12, padding: 0 }} />')).toHaveLength(1)
  })

  it('CSS takes every spacing and type size from a token', () => {
    const violations = cssFiles.flatMap((file) => cssViolations(file, readFileSync(join(SRC, file), 'utf8')))
    expect(violations, `\n${violations.join('\n')}\n`).toEqual([])
  })

  it('TSX takes every spacing and type size from the scale', () => {
    const violations = tsxFiles.flatMap((file) => tsxViolations(file, readFileSync(join(SRC, file), 'utf8')))
    expect(violations, `\n${violations.join('\n')}\n`).toEqual([])
  })
})
