-- Refresh the "Web 2 Mob" ICP's sub-industries and their per-industry include
-- keywords with the health/wellness taxonomy (23 sub-industries).
-- Follows migration 044's scoping: include keywords are PER-industry (here);
-- the ICP-wide exclude list (icps.exclude_keywords) is left untouched.
--
-- Data edits normally happen in-app, but this is a bulk replace of every
-- sub-industry, so it ships as a one-shot migration. Guarded on the ICP
-- existing so it no-ops on a DB where the 043 seed hasn't been applied.

do $$
declare
  v_icp_id bigint;
begin
  select id into v_icp_id from icps where lower(name) = lower('Web 2 Mob');
  if v_icp_id is null then
    raise notice 'Web 2 Mob ICP not found; skipping industry refresh';
    return;
  end if;

  -- Replace the whole sub-industry set (no child tables reference these rows).
  delete from icp_industries where icp_id = v_icp_id;

  insert into icp_industries (icp_id, name, include_keywords) values
    (v_icp_id, 'Wellness Business & Practice Management Software (B2B)', array['gym management', 'spa management', 'salon booking', 'studio management', 'wellness booking', 'wellness marketplace', 'practitioner management', 'therapist practice management', 'coaching software', 'coaching platform', 'client portal', 'nutrition software', 'workout builder', 'fitness SaaS', 'wellness SaaS', 'class scheduling software', 'appointment booking software', 'booking system', 'front desk software', 'membership management', 'member management software', 'yoga studio software', 'pilates studio software', 'fitness studio software', 'martial arts school software', 'dance studio software', 'personal trainer software', 'PT software', 'client management for coaches', 'practice management', 'clinic management software', 'allied health software', 'physiotherapy software', 'physical therapy software', 'chiropractic software', 'massage therapy software', 'acupuncture software', 'EHR for therapists', 'EMR for wellness', 'intake forms', 'HIPAA-compliant scheduling', 'waitlist management', 'package & membership billing']),
    (v_icp_id, 'Telehealth & Virtual Care Platforms', array['telehealth', 'telemedicine', 'telehealth platform', 'patient portal', 'digital health', 'virtual care', 'virtual clinic', 'virtual-first care', 'video consultation', 'online doctor', 'online GP', 'e-prescription', 'asynchronous care', 'direct-to-consumer healthcare', 'DTC health', 'online pharmacy', 'specialty telehealth', 'dermatology telehealth', 'online psychiatry', 'virtual urgent care', 'second opinion platform', 'e-visit', 'remote consultations', 'hybrid care', 'care navigation', 'patient engagement platform', 'patient communication', 'medical scheduling']),
    (v_icp_id, 'Care Coordination, Caregiving & Senior Health', array['senior wellness', 'chronic disease management', 'care coordination', 'collaborative care', 'care team', 'care plan software', 'family caregiving', 'caregiver app', 'caregiver support', 'eldercare', 'elder care', 'aging in place', 'senior care technology', 'agetech', 'home care software', 'home health software', 'care agency software', 'remote patient monitoring', 'RPM', 'patient monitoring', 'medication adherence', 'medication management', 'pill reminder', 'medication reminder', 'discharge planning', 'transitional care', 'long-term care software', 'assisted living software', 'dementia care', 'care management platform']),
    (v_icp_id, 'Clinical Mental & Behavioral Health', array['mental health app', 'therapy platform', 'CBT app', 'DBT app', 'behavioral health', 'mental health', 'addiction recovery', 'sobriety app', 'kids mental health', 'anxiety', 'depression', 'digital therapeutics', 'online therapy', 'teletherapy', 'virtual therapy', 'e-therapy', 'counseling platform', 'online counseling', 'psychiatry platform', 'psychedelic therapy', 'ketamine therapy', 'IOP', 'intensive outpatient', 'eating disorder recovery', 'OCD treatment', 'PTSD', 'trauma-informed care', 'grief support', 'peer support platform', 'mental health screening', 'measurement-based care', 'blended care', 'youth mental health', 'teen therapy', 'family therapy platform', 'couples therapy online', 'EAP platform', 'crisis support']),
    (v_icp_id, 'Consumer Mindfulness & Mental Wellness', array['meditation', 'mindfulness', 'breathwork', 'guided meditation', 'meditation app', 'breathwork app', 'journaling', 'affirmations', 'affirmation', 'manifestation', 'manifesting', 'astrology', 'horoscope', 'spirituality', 'self-care', 'self-care app', 'mental wellness', 'stress management', 'stress reduction', 'burnout', 'emotional tracking', 'emotion tracking', 'mood tracker', 'sound healing', 'sound bath', 'hypnotherapy', 'hypnosis app', 'gratitude journal', 'guided journaling', 'mindfulness for teams', 'meditation library', 'spiritual wellness', 'tarot', 'numerology', 'inner work', 'somatic', 'nervous system regulation', 'vagus nerve', 'cold plunge', 'sauna wellness', 'mindset coaching']),
    (v_icp_id, 'Nutrition & Diet Tech', array['nutrition tracker', 'calorie tracker', 'food tracking', 'food tracker', 'meal planning', 'meal planner', 'AI food scanner', 'macro tracker', 'dietitian platform', 'nutrition coaching', 'nutrition software', 'nutrition', 'fasting app', 'gut health', 'sports nutrition', 'registered dietitian software', 'RD platform', 'nutritionist software', 'meal prep', 'recipe planning', 'grocery list app', 'diet plan software', 'weight management', 'weight loss program', 'GLP-1 companion', 'medical weight loss', 'metabolic health', 'blood sugar tracking', 'glucose monitoring', 'CGM companion', 'diabetes nutrition', 'keto', 'intermittent fasting', 'plant-based nutrition', 'food sensitivity', 'elimination diet', 'microbiome', 'personalized nutrition', 'nutrigenomics', 'supplement recommendations', 'hydration tracking']),
    (v_icp_id, 'Fitness & Training Tech', array['fitness coaching', 'personal training', 'workout app', 'fitness platform', 'training software', 'fitness app', 'fitness tech', 'fittech', 'online coaching', 'athlete recovery', 'workout programming', 'strength programming', 'training plan builder', 'online fitness coaching', 'hybrid coaching', 'running coach app', 'cycling training', 'triathlon training', 'endurance training platform', 'marathon training', 'sports team management', 'team sports software', 'athlete management', 'athlete monitoring', 'sports science platform', 'performance tracking', 'movement assessment', 'exercise prescription', 'rehab exercise software', 'home workout', 'virtual fitness', 'on-demand fitness', 'live fitness classes', 'fitness community', 'challenge app']),
    (v_icp_id, 'Corporate & Employee Wellness ⭐ proven', array['corporate wellness', 'employee wellness', 'workplace wellbeing', 'wellness challenge', 'employee wellbeing platform', 'employee benefits', 'wellness benefits', 'health benefits navigation', 'employee assistance program', 'EAP', 'workforce mental health', 'workplace mental health', 'burnout prevention', 'employee engagement wellness', 'step challenge', 'team challenge', 'occupational health', 'ergonomics software', 'workplace safety wellness', 'wellness stipend', 'lifestyle spending account', 'benefits marketplace', 'HR wellness', 'benefits administration', 'benefits platform', 'benefits enrollment', 'total rewards', 'benefits communication', 'health plan navigation', 'healthcare navigation', 'care advocacy', 'employee recognition', 'rewards platform', 'employee engagement platform', 'employee experience platform', 'pulse survey', 'culture platform', 'financial wellness', 'financial wellbeing', 'earned wage access', 'employee financial health', 'fertility benefits', 'family benefits', 'caregiver benefits', 'menopause at work', 'mental health benefits', 'therapy benefits', 'musculoskeletal benefits', 'cancer support benefits', 'frontline employee wellbeing', 'deskless workforce', 'shift worker health', 'fatigue management', 'workforce safety', 'driver wellness', 'workplace coaching', 'leadership coaching platform', 'resilience training', 'manager training', 'wellbeing coaching', 'health plan engagement', 'member engagement', 'wellness rewards insurance', 'incentive-based wellness']),
    (v_icp_id, 'Sleep & Recovery Tech', array['sleep tracking', 'sleep tech', 'sleep tracker', 'sleep sounds', 'insomnia', 'recovery app', 'sleep coaching', 'CBT-I', 'sleep improvement program', 'sleep clinic software', 'sleep apnea', 'circadian health', 'sleep hygiene', 'readiness score', 'HRV tracking', 'recovery tracking', 'rest and recovery', 'nap app', 'white noise', 'sleep stories']),
    (v_icp_id, 'Femtech & Life-Stage Health', array['femtech', 'women''s health', 'cycle tracker', 'fertility app', 'pregnancy app', 'prenatal app', 'postpartum', 'menopause app', 'pelvic health', 'fertility clinic software', 'IVF platform', 'egg freezing', 'fertility benefits', 'ovulation tracking', 'hormone health', 'hormone testing', 'PCOS', 'endometriosis', 'doula platform', 'midwife software', 'lactation support', 'breastfeeding app', 'baby tracker', 'parenting app', 'maternal health', 'menopause care platform', 'perimenopause', 'men''s health', 'testosterone clinic', 'sexual wellness', 'sexual health', 'intimacy app', 'contraception platform']),
    (v_icp_id, 'Longevity, Preventive & Diagnostic Health', array['longevity platform', 'longevity', 'preventive health', 'biomarker tracking', 'health optimization', 'biohacking', 'functional medicine', 'holistic health', 'data-driven health', 'AI-powered health', 'personalized wellness', 'evidence-based wellness', 'at-home testing', 'at-home lab tests', 'blood testing platform', 'lab results dashboard', 'health screening', 'executive health', 'preventive care platform', 'DNA testing', 'genomics', 'genetic testing', 'epigenetics', 'biological age', 'healthspan', 'precision health', 'precision medicine', 'wearable data platform', 'health data aggregation', 'quantified self', 'VO2 max', 'body composition', 'full-body MRI', 'concierge medicine', 'integrative medicine', 'naturopathic']),
    (v_icp_id, 'Chronic Condition & Digital Therapeutics', array['digital therapeutics', 'chronic disease management', 'symptom tracker', 'diabetes management', 'blood pressure management', 'hypertension program', 'cardiac rehab', 'cardiovascular health', 'MSK', 'musculoskeletal', 'digital physical therapy', 'back pain program', 'chronic pain management', 'pain tracking', 'migraine tracker', 'asthma management', 'COPD', 'respiratory health', 'oncology support', 'cancer care platform', 'survivorship', 'IBS app', 'IBD management', 'autoimmune', 'condition management platform', 'disease management', 'patient adherence', 'care pathways', 'prescription digital therapeutic', 'PDT']),
    (v_icp_id, 'Habit, Behavior Change & Quit Tech', array['habits', 'habit tracker', 'daily tracking', 'quit app', 'behavior change platform', 'habit coaching', 'accountability app', 'streak tracker', 'quit smoking', 'stop smoking', 'quit vaping', 'nicotine cessation', 'quit drinking', 'alcohol-free', 'mindful drinking', 'sober curious', 'gambling recovery', 'screen time reduction', 'digital detox', 'dopamine detox', 'goal tracking', 'routine builder', 'atomic habits']),
    (v_icp_id, 'Neurodiversity, Special Populations & Therapy Services', array['ADHD app', 'ADHD coaching', 'autism support', 'ABA software', 'ABA practice management', 'speech therapy platform', 'teletherapy for kids', 'occupational therapy software', 'pediatric therapy', 'early intervention', 'special needs', 'neurodiversity', 'dyslexia support', 'executive function coaching', 'IEP management', 'disability support platform', 'assistive health technology']),
    (v_icp_id, 'Community, Challenges & Purpose-Driven Fitness', array['wellness challenge', 'charity fitness', 'fitness fundraising', 'charity challenge', 'virtual race', 'virtual run', 'race registration platform', 'event registration fitness', 'peer-to-peer fundraising', 'move for a cause', 'steps for charity', 'running club platform', 'cycling club', 'fitness community platform', 'social fitness', 'leaderboard app', 'team challenge platform', 'activity challenge']),
    (v_icp_id, 'Health & Wellness Education / E-Learning', array['health education platform', 'medical education', 'medical e-learning', 'healthcare e-learning', 'CME', 'continuing medical education', 'continuing education for nurses', 'nursing education', 'nursing CEU', 'CEU platform', 'healthcare LMS', 'healthcare training', 'clinical training', 'clinical skills training', 'medical simulation', 'healthcare compliance training', 'HIPAA training', 'OSHA healthcare training', 'first aid training', 'CPR training', 'BLS certification', 'ACLS', 'health coach certification', 'wellness certification', 'personal trainer certification', 'fitness certification', 'yoga teacher training', 'YTT', 'pilates certification', 'nutrition certification', 'nutrition courses', 'wellness courses', 'online health courses', 'wellness course marketplace', 'patient education', 'patient education platform', 'health literacy', 'disease education', 'medication education', 'caregiver training', 'mental health training', 'mental health first aid', 'therapist continuing education', 'CE for therapists', 'doula training', 'midwifery education', 'lactation consultant training', 'medical exam prep', 'USMLE prep', 'NCLEX prep', 'MCAT prep', 'allied health education', 'public health education', 'health promotion', 'wellness workshops', 'microlearning healthcare', 'cohort-based health courses', 'health coaching academy', 'med school prep', 'physician upskilling']),
    (v_icp_id, 'Clinical Trials & Research Tech', array['clinical trials platform', 'clinical trial software', 'patient recruitment', 'trial recruitment', 'decentralized clinical trials', 'DCT', 'virtual trials', 'hybrid trials', 'ePRO', 'eCOA', 'eConsent', 'electronic informed consent', 'patient-reported outcomes', 'trial participant engagement', 'participant retention', 'research study platform', 'study management', 'CTMS', 'site management software', 'real-world evidence', 'RWE', 'real-world data', 'clinical data capture', 'EDC', 'patient registry', 'research recruitment marketplace', 'trial matching', 'clinical research technology', 'longitudinal study platform']),
    (v_icp_id, 'Dental, Vision & Hearing Tech', array['dental software', 'dental practice management', 'dental clinic software', 'teledentistry', 'DSO software', 'dental group platform', 'orthodontic software', 'clear aligners', 'aligner treatment monitoring', 'oral health app', 'dental patient engagement', 'dental membership plans', 'optometry software', 'eye care platform', 'optical practice management', 'vision therapy', 'online eye exam', 'contact lens subscription', 'eyewear platform', 'teleoptometry', 'myopia management', 'teleaudiology', 'hearing health', 'hearing test online', 'hearing aid companion', 'audiology practice software', 'tinnitus app']),
    (v_icp_id, 'Healthcare Staffing & Workforce', array['healthcare staffing platform', 'medical staffing software', 'nurse staffing', 'nursing marketplace', 'nurse jobs platform', 'per diem nursing', 'PRN staffing', 'locum tenens platform', 'physician staffing', 'allied health staffing', 'caregiver marketplace', 'caregiver staffing', 'home care staffing', 'healthcare gig economy', 'shift scheduling healthcare', 'nurse scheduling software', 'medical scheduling workforce', 'credentialing software', 'healthcare credentialing', 'license verification', 'float pool management', 'workforce management healthcare', 'travel nursing platform', 'healthcare recruiting software']),
    (v_icp_id, 'Pharmacy & Medication Tech', array['pharmacy software', 'pharmacy management system', 'pharmacy platform', 'e-pharmacy', 'online pharmacy platform', 'digital pharmacy', 'prescription delivery', 'medication delivery', 'prescription savings', 'drug discount platform', 'prescription discount', 'specialty pharmacy', 'compounding pharmacy software', 'telepharmacy', 'pharmacist consultation', 'medication sync', 'refill management', 'prescription refill', 'pharmacy e-commerce', 'mail order pharmacy', 'medication packaging', 'pill pack', 'pharmacy patient engagement', 'medication therapy management', 'MTM']),
    (v_icp_id, 'Wellness Travel, Retreats & Medical Tourism', array['wellness retreats', 'retreat booking', 'retreat marketplace', 'retreat management software', 'wellness travel', 'wellness tourism', 'spa resort platform', 'spa booking platform', 'destination wellness', 'yoga retreat', 'yoga holiday', 'fitness retreat', 'detox retreat', 'meditation retreat', 'health resort', 'medical tourism', 'medical travel', 'health tourism platform', 'medical travel facilitator', 'dental tourism', 'surgery abroad', 'wellness concierge', 'longevity retreat', 'hot springs booking', 'ayurveda retreat']),
    (v_icp_id, 'Student & Campus Health', array['student mental health', 'student wellbeing platform', 'campus counseling', 'university counseling center', 'college mental health', 'student telehealth', 'campus health services', 'student health platform', 'school health software', 'school nurse software', 'health office software', 'K-12 wellness', 'student wellness screening', 'SEL platform', 'social emotional learning', 'student assistance program', 'campus recreation software', 'university fitness', 'student support platform', 'higher ed wellbeing', 'student crisis support', 'teen wellbeing school']),
    (v_icp_id, 'General / Catch-All Health & Wellness', array['wellness app', 'health app', 'wellbeing platform', 'wellness tech', 'health tech', 'healthtech', 'wellness platform', 'digital wellness', 'health coaching', 'wellness coaching', 'wellness', 'health & wellness', 'mobile health', 'health innovation', 'wellness startup', 'wellness dashboard', 'mhealth', 'consumer health', 'connected health', 'e-health', 'ehealth', 'health platform', 'care platform', 'wellbeing app', 'wellness solution', 'health engagement']);
end $$;
